### ISSUE TITLE
GPIO for antenna configuration is not working anymore

### ISSUE THREAD

**Issue by aircable** [bisonscience/ESP32-M1-Reach-Out#1]
This is the code from your technical document:
```
        config_gpio.gpio_cfg[0].gpio_select = 1; 
        config_gpio.gpio_cfg[0].gpio_num = LIGHTS_GPIO_LED_BLUE;       // Antenna TX switch -- blue LED
        config_gpio.gpio_cfg[1].gpio_select = 1; 
        config_gpio.gpio_cfg[1].gpio_num = LIGHTS_GPIO_LED_RED;      // Antenna RX switch -- red LED
        config_gpio.gpio_cfg[2].gpio_select = 0; 
        config_gpio.gpio_cfg[3].gpio_select = 0; 

        wifi_ant_config_t m_ant;
        m_ant.rx_ant_mode = WIFI_ANT_MODE_ANT1; 
        m_ant.rx_ant_default = WIFI_ANT_MODE_ANT1; 
        m_ant.tx_ant_mode = WIFI_ANT_MODE_ANT0; 
        m_ant.enabled_ant0 = 1;
        m_ant.enabled_ant1 = 2;
        if(( err = esp_wifi_set_ant_gpio( &config_gpio )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi gpio: %s\n", TAG, esp_err_to_name( err ));
        }
        if(( err = esp_wifi_set_ant( &m_ant )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi ant: %s\n", TAG, esp_err_to_name( err ));
        }
```
I connected two LEDs to show transmit and receive of the Wifi code.
Unfortunately, after upgrading to the latest IDF, this code does not work anymore. 
Any insight from you why? You sure the index for enable_antx are correct?

**Comment by bisonscience** [comment]
Hi Juergen,

I haven't tested this code on the latest IDF, I can confirm the enable_antx is correct. All the work on the code to test hardware was done on Ver 4.1.

Will come back to you once I have tested on the latest release .

Brgds
________________________________
From: Juergen Kienhoefer ***@***.***>
Sent: Friday, April 16, 2021 11:09 AM
To: bisonscience/ESP32-M1-Reach-Out ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bisonscience/ESP32-M1-Reach-Out] GPIO for antenna configuration is not working anymore (#1)


This is the code from your technical document:

        config_gpio.gpio_cfg[0].gpio_select = 1;
        config_gpio.gpio_cfg[0].gpio_num = LIGHTS_GPIO_LED_BLUE;       // Antenna TX switch -- blue LED
        config_gpio.gpio_cfg[1].gpio_select = 1;
        config_gpio.gpio_cfg[1].gpio_num = LIGHTS_GPIO_LED_RED;      // Antenna RX switch -- red LED
        config_gpio.gpio_cfg[2].gpio_select = 0;
        config_gpio.gpio_cfg[3].gpio_select = 0;

        wifi_ant_config_t m_ant;
        m_ant.rx_ant_mode = WIFI_ANT_MODE_ANT1;
        m_ant.rx_ant_default = WIFI_ANT_MODE_ANT1;
        m_ant.tx_ant_mode = WIFI_ANT_MODE_ANT0;
        m_ant.enabled_ant0 = 1;
        m_ant.enabled_ant1 = 2;
        if(( err = esp_wifi_set_ant_gpio( &config_gpio )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi gpio: %s\n", TAG, esp_err_to_name( err ));
        }
        if(( err = esp_wifi_set_ant( &m_ant )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi ant: %s\n", TAG, esp_err_to_name( err ));
        }


I connected two LEDs to show transmit and receive of the Wifi code.
Unfortunately, after upgrading to the latest IDF, this code does not work anymore.
Any insight from you why? You sure the index for enable_antx are correct?

**Comment by aircable** [comment]
Thank you very much. With the latest IDF, the LEDs are being "captured" by
the esp_wifi_set_ant_gpio function. Previous status is being reset and both
LEDs go out after the function call. But neither transmit or receive event
will turn on the LED. I can confirm that it worked before but not anymore.
No code change. My LEDs are driven by the GPIO, meaning high is ON. I have
also tried to initialize the GPIO in different ways, but the
internal esp_wifi_set_ant_gpio will reset anything.

This is the IDF version I use:

   - Module or chip used: ESP32-U4WDH and ESP32-D0WD-V3
   - IDF version v4.4-dev-930-ga6f33a9d3
   - Build System: idf.py
   - Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0

**Comment by bisonscience** [comment]
Hi Juergen,

Thanks for the details. Can you please direct me to Ver4.4 releases, I have the latest master and believe it's Ver4.2. for ESP32. I did see some notes for Ver4.4 for ESP32-S3 but no where to find the release.

BRgds
Manimaran Kanesan

________________________________

**Comment by aircable** [comment]
You can just close the git repo:
`git clone https://github.com/espressif/esp-idf.git`

**Comment by bisonscience** [comment]
This issue now closed.

**Comment by aircable** [comment]
I updated to IDF v4.4-dev-960-gcf457d412, still does not work. Here is my init routine.
Is there anything wrong in the order of initialization steps?
`
// Wifi initialization
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();

    esp_event_handler_instance_t instance_any_id;
    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
                                                        ESP_EVENT_ANY_ID,
                                                        &wifi_event_handler,
                                                        NULL,
                                                        &instance_any_id));


    if(( err = esp_wifi_init(&cfg) ) != ESP_OK ) {
        fprintf( stderr, "%s: wifi init: %s\n", TAG, esp_err_to_name( err ));
    }

        // use antenna configuration to enable visual LED in wifi 

        wifi_ant_gpio_config_t config_gpio; 
        config_gpio.gpio_cfg[0].gpio_select = 1; 
        config_gpio.gpio_cfg[0].gpio_num = LIGHTS_GPIO_LED_BLUE;       // Antenna TX switch -- blue LED
        config_gpio.gpio_cfg[1].gpio_select = 1; 
        config_gpio.gpio_cfg[1].gpio_num = LIGHTS_GPIO_LED_RED;      // Antenna RX switch -- red LED
        config_gpio.gpio_cfg[2].gpio_select = 0; 
        config_gpio.gpio_cfg[3].gpio_select = 0; 

        wifi_ant_config_t m_ant;
        m_ant.rx_ant_mode = WIFI_ANT_MODE_ANT1; 
        m_ant.rx_ant_default = WIFI_ANT_MODE_ANT1; 
        m_ant.tx_ant_mode = WIFI_ANT_MODE_ANT0; 
        m_ant.enabled_ant0 = 1;
        m_ant.enabled_ant1 = 2;
        if(( err = esp_wifi_set_ant_gpio( &config_gpio )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi gpio: %s\n", TAG, esp_err_to_name( err ));
        }
        if(( err = esp_wifi_set_ant( &m_ant )) != ESP_OK ) {
            fprintf( stderr, "%s: wifi ant: %s\n", TAG, esp_err_to_name( err ));
        }
    // must start wifi to listen
    esp_wifi_start();
    
`

**Comment by aircable** [comment]
I downgraded to idf-4.3-dev-1197 and can confirm that the code works with this version.
I filed a bug report on esp-idf. No need to reopen the case.

**Comment by aircable** [comment]
see: https://github.com/espressif/esp-idf/issues/6930
